### PR TITLE
Fixes #8 Pre-release adjustments

### LINKED ISSUE #8: Pre-release adjustments
Project is ready for releasing, but it'd be better to do a few adjustments to avoid issues down the line:

* Use version  ```0.1``` instead of ```0.0.1```, just to align with the other Infinispan connectors;
* Typo in the README.md: instead of "actually", use "currently"
* It'd be better to use a multi-module project where the current code would be located under ```core``` module name; the artifact can still have the same GAV as now. This allows to add new modules such as samples, tutorials and other optional jars. For an example of this structure, check https://github.com/infinispan/protostream/ or  https://github.com/infinispan/infinispan-hadoop/

### PR DESCRIPTION
**Pull request by oscerd**
This should fix #8

### CODE REVIEW

**Comment by oscerd** [comment]
@gustavonalle let me know if something is missing when you free.

**Comment by gustavonalle** [comment]
Merged, thanks @oscerd 
Are we need for the 0.1 version release?

**Comment by oscerd** [comment]
Yes, I think we are :-)

**Comment by gustavonalle** [comment]
ok, I will do the release

**Pull request merged**
